# Generated by Django 5.2 on 2025-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
    ]
