# Generated by Django 5.2 on 2025-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noots', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='noots',
            name='user_id',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
